export const carMarques: string[] = [
    'Dacia',
    'Renault',
    'Peugeot',
    'Citroën',
    'Volkswagen',
    'Ford',
    'Toyota',
    'Nissan',
    'Hyundai',
    'Kia',
    'Mercedes-Benz',
    'BMW',
    'Audi',
    'Fiat',
    'Opel',
    'Suzuki',
    'Mazda',
    'Volvo',
    'Jeep',
    'Land Rover',
    'Mitsubishi',
    'Lexus',
    'Honda',
    'Subaru',
    'Skoda',
    'Seat',
    'Chevrolet',
    'Tesla',
    'Jaguar',
    'Mini',
    'Alfa Romeo',
    'Porsche',
    'Smart',
    'DS Automobiles',
    'Infiniti',
    'Abarth',
    'Maserati',
    'Bentley',
    'Lamborghini',
    'Ferrari',
    'Bugatti',
    'McLaren',
    'Rolls-Royce',
    'Aston Martin',
    'Acura',
    'Buick',
    'Cadillac',
    'Chrysler',
    'Dodge',
    'GMC',
    'Hummer',
    'Isuzu',
    'Lincoln',
    'Pontiac',
    'Saturn',
    'Saab',
    'Koenigsegg',
    'Lotus',
    'Maybach',
    'Pagani',
    'Spyker',
    'TVR',
    'Vector',
    'Wuling',
    'Zenvo',
    'Geely',
    'BYD',
    'Changan',
    'Great Wall',
    'Haval',
    'JAC Motors',
    'Lifan',
    'Luxgen',
    'Roewe',
    'Brilliance',
    'Chery',
    'Dongfeng',
    'FAW',
    'Haima',
    'MG',
    'Trumpchi',
    'Venucia',
    'Yema',
    'Zotye',
    'BAIC',
    'Landwind',
    'Hongqi',
    'WEY',
    'Wuling'
];

export const typesVoitures: string[] = [
    'Berline',
    'SUV',
    'Coupé',
    'Cabriolet',
    'Monospace',
    'Utilitaire',
    'Compacte',
    'Sportive',
    'Tout-terrain',
    'Pick-up',
    'Van',
    'Fourgonnette',
    'Mini-fourgonnette',
    'Limousine'
];

export const moroccanCities: string[] = [
    "Rabat",
    "Casablanca",
    "Marrakech",
    "Tangier",
    "Fes",
    "Agadir",
    "Oujda",
    "Tetouan",
    "Kenitra",
    "Safi",
    "Meknes",
    "El Jadida",
    "Nador",
    "Laayoune",
    "Dakhla",
    "Khemisset",
    "Ifrane",
    "Errachidia",
    "Azrou",
    "Chefchaouen",
    "Taroudant",
    "Beni Mellal",
    "Khouribga",
    "El Hoceima",
    "Settat",
    "Sidi Kacem",
    "Sidi Slimane",
    "Fkih Ben Salah",
    "Jorf Lasfar",
    "Ouarzazate",
    "Boujdour",
    "Tiznit",
    "Sefrou",
    "Oulad Teima",
    "Salé",
    "Rissani",
    "Midelt",
    "Tanger-Tetouan",
    "Azilal",
    "Mediouna",
    "Youssoufia",
    "Berkane",
    "Taza",
    "Guelmim"
  ];
  